title: ToF Guide and Resources
description: A collection of guide and resources for Tower of Fantasy game.
theme: just-the-docs
color_scheme: dark

plugins:
  - jekyll-seo-tag

aux_links:
  "Source":
    - "https://github.com/NatsumeLS/ToF-Guide-Resources"

back_to_top: true
back_to_top_text: "Back to top"